version: "3"

services:

  nginx:
    restart: always
    image: nginx
    container_name: ckan_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt/certs:/etc/nginx/certs
      - ./letsencrypt/www:/var/www/letsencrypt
      - ./nginx_conf:/etc/nginx/conf.d

  ckan:
    container_name: ckan
    build:
      context: ckan/
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ckan_storage:/var/lib/ckan

  datapusher:
    container_name: datapusher
    build:
      context: datapusher/
    ports:
      - "8800:8800"

  db:
    container_name: db
    build:
      context: postgresql/
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    build:
      context: solr/

  redis:
    container_name: redis
    image: redis:alpine

  letsencrypt:
    build: ./certbot
    command: /bin/true
    volumes:
      - ./letsencrypt/certs:/etc/letsencrypt
      - ./letsencrypt/www:/var/www/letsencrypt

volumes:
  ckan_storage:
  pg_data:
